name: Run Tests

on:
  push:
    branches:
      - development
      - main
  pull_request:
    branches:
      - development
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint
        continue-on-error: true

      - name: Run Jest tests with coverage
        run: npm test -- --coverage

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results/

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/

  deploy:
      runs-on: ubuntu-latest
      needs: test
      if: github.ref == 'refs/heads/main'

      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Set up Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 18
            cache: 'npm'
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}

        - name: Install dependencies
          run: npm ci --cache .npm --prefer-offline

        - name: Deploy to Amplify
          env:
            AMPLIFY_APP_ID: ${{ secrets.AWS_APP_ID }}
            AWS_REGION: ${{ secrets.AWS_REGION }}
            AMPLIFY_ENVIRONMENT: ${{ github.ref_name }}
          run: npx ampx pipeline-deploy --branch ${{ github.ref_name }} --app-id ${{ secrets.AWS_APP_ID }}

        - name: Upload Amplify build logs
          uses: actions/upload-artifact@v4
          with:
            name: amplify-build-logs
            path: amplify/backend/build.log